language: node_js
sudo: true
dist: trusty
node_js:
  - 10
  - 12
install:
  - yarn
script:
  - npm run lint
  - npm run test
notifications:
  email:
    on_success: change
    on_failure: change
after_success:
  - npm run coveralls
cache:
  directories:
  - node_modules
