language: node_js
sudo: true
os:
  - linux
  - osx
node_js:
  - 10
  - 12
script:
  - npm run lint
  - npm run test
notifications:
  email:
    on_success: change
    on_failure: change
after_success:
  - npm run coveralls
cache:
  directories:
  - node_modules
